import type { Metadata } from "next";
import Image from "next/image";
import { useTranslations } from "next-intl";
import { getTranslations } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import PageHero from "@/components/public/page-hero";
import PublicContainer from "@/components/public/public-container";
import CtaSection from "@/components/public/cta-section";
import { focusAreaKeys } from "@/components/public/content";
import { localizedMetadata } from "@/lib/i18n/metadata";
import type { Locale } from "@/i18n/routing";
import RevealOnScroll from "@/components/public/reveal-on-scroll";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const t = await getTranslations({ locale, namespace: "team" }); return localizedMetadata({ locale: locale as Locale, title: t("heroTitle"), description: t("heroDescription"), path: "/team" }); }
export default function TeamPage() { const t = useTranslations("team"); const home = useTranslations("home"); return <><PageHero eyebrow={t("heroEyebrow")} title={t("heroTitle")} description={t("heroDescription")} current={t("heroEyebrow")} /><section className="bg-[var(--paper)]"><PublicContainer><RevealOnScroll className="grid gap-12 py-20 sm:py-24 lg:grid-cols-[.8fr_1.2fr] lg:gap-20" stagger={120}><div><p className="eyebrow text-[var(--rams-red)]">{t("headEyebrow")}</p><div className="public-card-interaction mt-6 border border-[var(--border)] bg-white p-7"><div className="group relative aspect-[4/3] overflow-hidden bg-[var(--navy)]"><Image src="/assets/prof-ketut.jpg" alt={t("headPhotoAlt")} fill sizes="(max-width: 1024px) 100vw, 360px" className="public-image-zoom object-cover object-[center_24%]" /></div><h2 className="mt-7 font-display text-2xl font-semibold text-[var(--navy)]">{t("headName")}</h2><p className="mt-2 font-mono text-[0.62rem] uppercase tracking-[0.1em] text-[var(--rams-red)]">{t("leadership")}</p><p className="mt-3 text-sm leading-6 text-[var(--slate)]">{t("alignment")}</p><p className="mt-5 border-t border-[var(--border)] pt-4 font-mono text-[0.62rem] uppercase tracking-[0.1em] text-[var(--gray)]">{t("notExposed")}</p></div></div><div><p className="eyebrow text-[var(--ais-blue)]">{t("staffEyebrow")}</p><h2 className="mt-4 font-display text-3xl font-semibold tracking-[-0.04em] text-[var(--navy)]">{t("staffTitle")}</h2><p className="mt-5 max-w-xl text-base leading-7 text-[var(--slate)]">{t("staffDescription")}</p><RevealOnScroll className="mt-8 grid gap-3 sm:grid-cols-2" stagger={90}>{focusAreaKeys.map((key, index) => <div key={key} className="public-card-interaction border border-[var(--border)] bg-white p-5"><span className="font-mono text-[0.62rem] text-[var(--rams-red)]">0{index + 1}</span><p className="mt-5 font-display text-lg font-semibold text-[var(--navy)]">{home(`focus.${key}`)}</p></div>)}</RevealOnScroll></div></RevealOnScroll></PublicContainer></section><section className="border-y border-[var(--border)] bg-white"><PublicContainer className="py-16 sm:py-20"><RevealOnScroll className="border-l-2 border-[var(--rams-red)] pl-6 sm:pl-8"><p className="eyebrow text-[var(--ais-blue)]">{t("directoryNote")}</p><p className="mt-4 max-w-2xl text-base leading-7 text-[var(--slate)]">{t("directoryText")}</p><Link href="/contact" className="mt-6 inline-block text-sm font-semibold text-[var(--rams-red)]">{t("ask")} ↗</Link></RevealOnScroll></PublicContainer></section><CtaSection title={t("ctaTitle")} description={home("ctaDescription")} primary={home("primaryCta")} secondary={home("researchLink")} /></>; }
